version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/dev.db
      - NEXTAUTH_SECRET="your-secret-goes-here"
      - NEXTAUTH_URL="http://localhost:3000"
    volumes:
      - sqlite_data:/app/prisma
      - uploads:/app/public/uploads

volumes:
  sqlite_data:
  uploads: